
print("My Daily Routine")
print()
print("Note: Routine may vary for different days of the week")
print()
print("This one is for Saturday when I have school")
print()
print("1.Wake up at 5:00 AM")
print()
print("2.Brush my teeth")
print()
print("3.Drink milk")
print()
print("4.Change into my nylon clothes")
print()
print("5.Go to the rifle shooting range")
print()
print("6.Complete shooting by 6:45AM")
print()
print("7.Come home and bath")
print()
print("8.Change into my school uniform and go to school after breakfast.")
print()
print("9.Return from school at 3:40PM")
print()
print("10.Go to tennis at 4:00PM")
print()
print("11.Return and attend singing,keyboard,guitar class if present.")
print()
print("12.Complete H.W")
print()
print("13.Study some subjects for 3 hrs")
print()
print("14.Do some coding")
print()
print("15.Spend some family time during eating.")
print()
print("16.Sleep")
print()
print("Total study time in 1 week:", 3 * 7)
print()
print("And that is my routine on Saturdays! What's yours?")